version: '3.9'

services:
  web:
    image: tautiz/web4study:latest
    volumes:
      - ./project:/var/www/html/
    user: web:web
    ports:
      - 80:80
    environment:
      PHP_IDE_CONFIG: 'serverName=web.local'
      APACHE_SERVER_NAME: web.local
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html
      APACHE_RUN_USER: web
      APACHE_RUN_GROUP: web

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apache_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      PMA_USER: devuser
      PMA_PASSWORD: devpass
      UPLOAD_LIMIT: 2048
